create table users (
    player_tag varchar(32) primary key,
    username varchar(50) not null unique,
    email varchar(255) not null,
    password varchar(255) not null,
    registered_at timestamptz not null
);

create table auth_tokens (
    token varchar(512) primary key,
    token_type varchar(20) not null,
    player_tag varchar(32) not null references users(player_tag) on delete cascade
);

create table cards (
    id integer primary key,
    api_card_id integer,
    name varchar(120) not null,
    elixir integer,
    rarity varchar(40),
    arena integer,
    icon_url text,
    description text,
    data_json text not null,
    updated_at timestamptz not null
);

create table user_preferences (
    player_tag varchar(32) primary key references users(player_tag) on delete cascade,
    preferred_strategy varchar(40),
    min_elixir double precision,
    max_elixir double precision,
    preferred_card_ids_json text not null,
    excluded_card_ids_json text not null,
    updated_at timestamptz not null
);

create table profile_caches (
    player_tag varchar(32) primary key,
    player_name varchar(120),
    trophies integer,
    best_trophies integer,
    exp_level integer,
    current_deck_json text,
    rewards_json text not null,
    profile_data_json text not null,
    battle_stats_json text not null,
    updated_at timestamptz not null
);

create table rating_points (
    id bigint generated by default as identity primary key,
    player_tag varchar(32) not null,
    rating integer not null,
    changed_at timestamptz not null
);

create index idx_rating_points_player_tag on rating_points(player_tag);

create table decks (
    id bigint generated by default as identity primary key,
    owner_player_tag varchar(32) not null,
    name varchar(100),
    deck_type varchar(40) not null,
    strategy varchar(40),
    description text,
    quality_score double precision,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    cards_json text not null,
    metrics_json text not null
);

create index idx_decks_owner on decks(owner_player_tag);

create table public_decks (
    token varchar(80) primary key,
    deck_id bigint not null references decks(id) on delete cascade,
    public_url text not null,
    published_at timestamptz not null
);

create table comparisons (
    id bigint generated by default as identity primary key,
    player_tag varchar(32) not null,
    left_deck_json text not null,
    right_deck_json text not null,
    left_score double precision not null,
    right_score double precision not null,
    left_breakdown_json text not null,
    right_breakdown_json text not null,
    winner_side varchar(10) not null,
    result_description text not null,
    created_at timestamptz not null
);

create index idx_comparisons_player_tag on comparisons(player_tag);
